# Generated by Django 5.2.9 on 2025-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(
                default=False, verbose_name='Payment Status'),
        ),
    ]
