# Generated by Django 5.2.9 on 2025-12-06 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrollment_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(
                max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(
                max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(
                max_length=254, verbose_name='Email Address'),
        ),
    ]
