# Generated by Django 5.2.9 on 2026-01-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentannouncementreadstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='passcode',
            field=models.CharField(
                default='0000', max_length=4, verbose_name='Session Passcode'),
        ),
    ]
